'use client'

import {
  ArrowLeft,
  ArrowRight,
  ArrowRightFromLine,
  ArrowLeftFromLine,
  Bitcoin,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  DollarSign,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LineChart,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Shield,
  SunMedium,
  Trash,
  TrendingUp,
  User,
  Wallet,
  X,
  Zap,
  type Icon as LucideIcon,
} from "lucide-react"

export type Icon = typeof LucideIcon

export const Icons = {
  Logo: Bitcoin,
  Close: X,
  spinner: Loader2,
  ChevronLeft,
  ChevronRight,
  Trash,
  Post: FileText,
  Page: File,
  Media: Image,
  Settings,
  Billing: CreditCard,
  Ellipsis: MoreVertical,
  Add: Plus,
  Warning: HelpCircle,
  User,
  ArrowIn: ArrowLeftFromLine,
  ArrowOut: ArrowRightFromLine,
  Money: DollarSign,
  Crypto: Bitcoin,
  Balance: Wallet,
  Chart: LineChart,
  Trend: TrendingUp,
  ArrowRight,
  Help: HelpCircle,
  Pizza,
  Sun: SunMedium,
  Moon,
  Laptop,
  Bitcoin,
  DollarSign,
  TrendingUp,
  Token: Bitcoin,
  X,
  ChartLine: LineChart,
  Shield,
  Zap,
} as const